--Partie 2 
-- 4 creation des relations de la base de données 

CREATE TABLE SPORTIFS (
    IDSPORTIF  NUMBER,
    NOM     VARCHAR(50),
    PRENOM  VARCHAR(50),
    SEXE    VARCHAR(1),
    AGE     NUMBER,
    IDSPORTIFCONSEILLER NUMBER ,
    CONSTRAINT pk_SPORTIFS PRIMARY KEY(IDSPORTIF),
    CONSTRAINT cs_SEXE CHECK (lower(SEXE) IN ('m','f')),
    CONSTRAINT fk_SPORTIFS FOREIGN KEY(IDSPORTIFCONSEILLER) REFERENCES SPORTIFS(IDSPORTIF) ON DELETE CASCADE
);


CREATE TABLE SPORTS (
    IDSPORT NUMBER ,
    LIBELLE VARCHAR(40),
    CONSTRAINT pk_SPORTS PRIMARY KEY(IDSPORT)
);

CREATE TABLE GYMNASES (
    IDGYMNASE NUMBER  ,
    NOMGYMNASE VARCHAR(100),
    ADRESSE     VARCHAR(150),
    VILLE       VARCHAR(50),
    SURFACE     NUMBER,
    CONSTRAINT pk_GYMNASES PRIMARY KEY(IDGYMNASE)
);

CREATE TABLE ARBITRER (
    IDSPORTIF   NUMBER , 
    IDSPORT     NUMBER ,
    CONSTRAINT pk_ARBITRER PRIMARY KEY(IDSPORTIF,IDSPORT),
    CONSTRAINT fk_SPORTIF_ARBITRER FOREIGN KEY(IDSPORTIF) REFERENCES SPORTIFS (IDSPORTIF) ON DELETE CASCADE,
    CONSTRAINT fk_SPORT_ARBITRER  FOREIGN KEY (IDSPORT) REFERENCES SPORTS (IDSPORT) ON DELETE CASCADE
);

CREATE TABLE ENTRAINER (
    IDSPORTIFENTRAINEUR     NUMBER , 
    IDSPORT     NUMBER ,
    CONSTRAINT pk_ENTRAINER PRIMARY KEY (IDSPORT,IDSPORTIFENTRAINEUR),
    CONSTRAINT fk_SPORTIFS_ENTRAINER FOREIGN KEY (IDSPORT) REFERENCES SPORTS(IDSPORT) ON DELETE CASCADE,
    CONSTRAINT fk_SPORTIFS_ENTRAINEUR2 FOREIGN KEY (IDSPORTIFENTRAINEUR) REFERENCES SPORTIFS (IDSPORTIF) ON DELETE CASCADE
);

CREATE TABLE JOUER (
    IDSPORTIF   NUMBER , 
    IDSPORT     NUMBER ,
    CONSTRAINT pk_JOUER PRIMARY KEY (IDSPORTIF,IDSPORT),
    CONSTRAINT fk_SPORT_JOUER FOREIGN KEY (IDSPORT) REFERENCES SPORTS(IDSPORT) ON DELETE CASCADE,
    CONSTRAINT fk_SPORTIFS_JOUER FOREIGN KEY (IDSPORTIF) REFERENCES SPORTIFS(IDSPORTIF) ON DELETE CASCADE
); 

CREATE TABLE SEANCES (
    IDGYMNASE   NUMBER , 
    IDSPORT     NUMBER  ,
    IDSPORTIFENTRAINEUR NUMBER ,
    JOUR        VARCHAR(8),
    HORAIRE     REAL,
    DUREE       NUMBER,
    CONSTRAINT ck_JOUR CHECK ( lower(JOUR) in ('samedi','dimanche','lundi','mardi','mercredi','jeudi','vendredi') ),
    CONSTRAINT fk_SEANCES_GYMNASE FOREIGN KEY (IDGYMNASE) REFERENCES GYMNASES (IDGYMNASE) ON DELETE CASCADE,
    CONSTRAINT fk_SEANCES_SPORT  FOREIGN KEY (IDSPORT) REFERENCES SPORTS (IDSPORT) ON DELETE CASCADE,
    CONSTRAINT fk_SEANCES_ENRTRAINER FOREIGN KEY (IDSPORTIFENTRAINEUR) REFERENCES SPORTIFS (IDSPORTIF) ON DELETE CASCADE,
    CONSTRAINT pk_SEANCES PRIMARY KEY (IDGYMNASE,IDSPORT,IDSPORTIFENTRAINEUR,JOUR,HORAIRE)
);

CREATE TABLE TableErreurs (
    adresse ROWID,
    utilisateur VARCHAR2(30),
    nomTable VARCHAR2(30),
    nomContrainte VARCHAR2(30)
    ); 


--5 ajout d l'attrbut DATECREATION de type date dans la relation GYMNASES
    ALTER TABLE GYMNASES ADD DATECREATION DATE NOT NULL ;
--6 Ajout de la contrainte sur les attribut sex et age de la table SPORTIF:
    ALTER TABLE SPORTIFS ADD CONSTRAINT ck_SPORTIFS_AGE CHECK (AGE IS NOT NULL);
    ALTER TABLE SPORTIFS ADD CONSTRAINT ck_SPORTIFS_SEXE CHECK (SEXE IS NOT NULL);
--7 modifier longeur de l'attribut prenom
    ALTER TABLE SPORTIFS MODIFY ( PRENOM VARCHAR(45));
--8  Supprimer la colonne dateCreation dans la table gymnase. 
    ALTER TABLE GYMNASES DROP COLUMN DATECREATION ;
    -- verifier
    desc  GYMNASES;
--9 Renommer la colonne ADRESSE dans la table gymnase par adressegym.    
    ALTER TABLE GYMNASES RENAME COLUMN ADRESSE TO adressegym;
    --verifier
    desc  GYMNASES;
--10 Ajout d'un domaine pour libelle :5
    ALTER TABLE SPORTS 
    ADD CONSTRAINT CK_SPORTS_LIBELLE CHECK (LOWER(LIBELLE) IN ('basket ball','volley ball','hand ball','tennis', 'hockey', 'badmington','ping pong','football', 'boxe'));
--11 


--12 
--@/home/goku/Code/SII/Abdd/tp1.sql

--SELECT 'DROP TABLE "' || TABLE_NAME || '" CASCADE CONSTRAINTS;' FROM user_tables;
