CREATE TABLESPACE GYMNASE_TBS2 DATAFILE '/home/goku/Code/SII/Abdd/TP3/Gymnasetbs2.dat' SIZE 100M AUTOEXTEND ON;

Create Temporary tablespace Gymnasetbs2_temps TEMPFILE '/home/goku/Code/SII/Abdd/TP3/GymnaseTbsTemps2.dat' SIZE 100M AUTOEXTEND ON;

CREATE USER DBAGYMNASE3 IDENTIFIED BY batata DEFAULT TABLESPACE GYMNASE_TBS2 TEMPORARY TABLESPACE Gymnasetbs2_temps;

